spring:
  application:
    name: apigateway

server:
  port: 8081

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


zuul:
  prefix: /api
  routes:
    category-management:
      path: /category-management/**
      serviceId: category-management
    comment-management:
      path: /comment-management/**
      serviceId: comment-management
    product-management:
      path: /product-management/**
      serviceId: product-management
    purchasing-management:
      path: /purchasing-management/**
      serviceId: purchasing-management
    user-management:
      path: /user-management/**
      serviceId: user-management

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: false